config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/about", to: "static_pages#about"
  get "/signup", to: "users#new"
  get "sessions/new"
  get "/about", to: "static_pages#about"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, only: %i(new create show)
  resources :categories, only: :index
  resources :lessons do
    resources :results
  end
  resources :words

  resources :users do
    member do
      get :following, :followers
    end
  end

 resources :relationships, only: %i(create destroy)
end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "error.error_html", error_count: t("error",
        count: @user.errors.count) %>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    <%= t "following" %>
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    <%= t "followers" %>
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to (image_tag current_user.avatar.url :small if current_user.avatar?), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to t("view_profile"), current_user %></span>
<span><%= link_to t("Word learned"), words_path(learned: 1) %></span>