config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/about", to: "static_pages#about"
  get "/signup", to: "users#new"
  get "sessions/new"
  get "/about", to: "static_pages#about"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, only: %i(new create show)
  resources :categories, only: :index
  resources :lessons do
    resources :results
  end
  resources :words

  resources :users do
    member do
      get :following, :followers
    end
  end

 resources :relationships, only: %i(create destroy)
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t "footer_html", author_href: link_to(t("author"), t("url.author")) %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("static_pages.about.title"), about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("main_title"), root_path, class: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("static_pages.home.title"), root_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("category"), categories_path %></li>
          <li><%= link_to t("word_list"), words_path %></li>
          <li><%= link_to t("users"), users_path %></li>
          <li class="dropdown">
            <%= link_to t("account"), "#", "data-toggle": "dropdown", class: "dropdown-toggle" %>
            <ul class="dropdown-menu">
              <li><%= link_to t("profile"), current_user %></li>
              <li><%= link_to t("settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t "title" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all",
     "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track":
     "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>